### ISSUE TITLE
wowman command doesn't work for me

### ISSUE THREAD

**Issue by skinofthesoul** [ogri-la/wowman#104]
Hey there,

first of all let me say that I absolutely **love** your work! I installed WoW Manager yesterday without a hitch, and ventured into Modland for the first time in my life. (Side note: I played for a while ten years ago, all the while remaining a total n00b, now I've come back to it because my kids have started playing. But I must say, playing under Linux has really become a total joy compared to ten years ago, thanks in no small part to people like you!)

However, I can't restart the programme by typing 'wowman' on the command line like it says in the readme, that only gets me a 'command not found'. Wildly guessing I'd say it might be a path issue? I'm on Kubuntu 19.10, and while I have been on Linux for the better part of the past two decades, I'm still not all that knowledgeable really. So this might be a really simple thing, but any pointers are much appreciated.

(On the other hand, I *can* still start the .jar file like I did the first time, so it's a) not a problem really and b) possibly this is the actual state of things and you've only forgotten to update the readme.)

Thank you again
Anna~

**Comment by torkus** [comment]
Sorry for the delay in getting back to you, I've been on holidays.

The `wowman` command line executable is only available for users of the [Arch Linux distribution](https://www.archlinux.org/), everybody else has to use `java -jar wowman...` 

The command line executable for Arch users is nothing special, it's just an executable shell script called "wowman" placed somewhere on your path whose contents look like this:

```
#/bin/bash
java -jar /path/to/file.jar "$@"
```

Arch Linux users get this because I maintain a [`wowman` package](https://github.com/ogri-la/wowman-pkgbuild) for them.

Maintaining many different types of releases takes time and effort. If you'd like to propose some code that attempted this, I'd be happy to look at it.

**Comment by torkus** [comment]
Feel free to re-open this ticket if you'd like some more help or if I've misunderstood your problem.
