### ISSUE TITLE
Unreadable text with dark GTK theme

### ISSUE THREAD

**Issue by armordecai** [ogri-la/wowman#105]
I've just come back to WoW after several years away, and this looks like a promising alternative to the basic command-line script I was using before (which no longer works with the addition of Cloudflare DDOS protection on Curse). However, there are some visual issues with a dark GTK theme. I'm using Linux Mint 19.2 with Cinnamon and the built-in Mint Y Dark theme.

- About half the rows in the addon list (I think these are the ones with updates available) and activity log (looks like all the "warn" level messages) have white backgrounds, but are still using the system default text color, which in my case is a very light gray that isn't legible on white. Moving the mouse over any row also gives it a white background.
- Some of the rows in the "search" tab have light green backgrounds (I think these are the ones I have installed already), with the same problem.
- The link in the "go" column are blue, which is too dark to read on the normal (dark background) rows.

Attached is a screenshot. Let me know if there's any other info that would be helpful!

![Screenshot from 2019-12-27 12-32-57](https://user-images.githubusercontent.com/8208500/71531797-2ee9a380-28a5-11ea-9869-bff0c629f0b5.png)

**Comment by torkus** [comment]
wow - that's all sorts of things.

I have a Mate environment I could switch to a dark theme to see if I can replicate this.

From your screenshot I can see most of the widgets are doing the right thing, but it looks to be the custom colours I'm forcing that are making this weird. I'll investigate these, but you may need to end up selecting a 'dark theme' or similar so I can calculate contrasts and such.

> I've just come back to WoW after several years away, and this looks like a promising alternative to the basic command-line script I was using before (which no longer works with the addition of Cloudflare DDOS protection on Curse)

Yes, that CDN issue, Twitch merger and 'Classic' support really did a number on the addon managers out there.

While I really appreciate your patronage, I maintain [a list of other addon managers](https://ogri-la.github.io/wow-addon-managers/) that you might find useful if you really prefer a terminal (javascript required),  particularly [instawow](https://github.com/layday/instawow) and [cursebreaker](https://github.com/AcidWeb/CurseBreaker).

**Comment by torkus** [comment]
I can replicate this now:

![screenshot-dark-native](https://user-images.githubusercontent.com/48790775/71536870-3f148800-2964-11ea-89b9-a9955cf46ed0.png)

(cinnamon has come a long way since I last looked at it)

I have two options to fixing this:

1. I figure out whether wowman is operating in a dark or light environment and set the colours accordingly. This might have to be a manual settings change by the user.
2. I provide a toggle to disable the 'native look and feel' which is doing it's best to make the Java Swing widgets look like the native widget set.

I have a TODO item to make the colours being used configurable by the user but I think it would be more work than number 2, which I could probably incorporate into the 0.11.0 release due before the end of the month.

For the time being I've attached a development version of wowman below with the native look and feel disabled so it's at least readable:

---

[wowman-0.11.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/4006559/wowman-0.11.0-unreleased-standalone.jar.zip)

sha256: bf4b0763dc8d0a337879fde2c1bb9bf95adb3c7592bc8cf007220a5d7be271b9

---

The standard `java -jar wowman-0.11.0-unreleased-standalone.jar.zip` should work, however if you're on **Arch** and using the latest `wowman` from the AUR then you could probably just do this:

```bash
cp wowman-0.11.0-unreleased-standalone.jar.zip /usr/share/java/wowman/wowman-0.10.2-standalone.jar
```

**Comment by armordecai** [comment]
The zip works, and the colors are legible, thanks! Unfortunately ignoring the system colors also ignores the system DPI, so the text is very small. If there's not an easy way to tell whether the system is using a dark theme in Java, a simple "light/dark" setting would be the next best thing, I think.

Now that I'm thinking about it, you could even avoid most of the issue by adding a "status" columns with icons (check mark for installed, etc. and Unicode glyphs are fine) instead of coloring the whole row. The only color left to worry about would be the link in the "go" column. That would also make it possible to sort by status and get all the addons with updates available at the top of the list.

> While I really appreciate your patronage, I maintain [a list of other addon managers](https://ogri-la.github.io/wow-addon-managers/) (javascript required) that you might find useful if you really prefer a terminal, particularly [instawow](https://github.com/layday/instawow) and [cursebreaker](https://github.com/AcidWeb/CurseBreaker).

I prefer a GUI, but I was using the terminal because a friend had already written it, and back then there weren't all these other options. I did try another one of the GUI options on your list, but it didn't seem to have a way to detect the addons I already have installed; yours almost gets them all -- would a list of the ones it missed be helpful?

**Comment by torkus** [comment]
> yours almost gets them all -- would a list of the ones it missed be helpful?

Couldn't hurt.

wowman supports wowinterface and curseforge and the development version you have also supports tukui. The process of matching installed addons to addons in the catalogue is called 'reconciliation' and it's a tricky thing to do because if exact matches aren't possible then I have to start using less precise matches and the possibility of mismatch goes up. 

There will always be addons that don't match and you'll have to go to the 'search' pane and re-install them. This could be for a number of different reasons. 

Once an addon is installed (or re-installed) through wowman there will always be an exact match unless the addon author deletes their addon from a host - which happens occasionally.

**Comment by armordecai** [comment]
Going through the list in more detail, it looks like the ones that didn't get matched fall into three categories:

1. There's a color code in the TOC title. (Kui Nameplates, Masque: Cainyx) This is probably fixable, as otherwise the TOC title matches what's on the download page.

2. Neither the TOC title nor the folder name match the addon's title on its download page. (HandyNotes plugins with various combinations of spaces vs camel-casing, or colon vs underscore)

3. The addon is really old and listed as outdated/abandoned on its download page. I'm guessing these are just not included in the catalog data, which is reasonable, since an addon that was last updated during MoP is probably never going to have any updates to download anyway.

**Comment by torkus** [comment]
> The addon is really old and listed as outdated/abandoned on its download page. I'm guessing these are just not included in the catalog data, which is reasonable, since an addon that was last updated during MoP is probably never going to have any updates to download anyway.

By default wowman uses a 'short' catalog, which has all of the addons since the beginning of the *previous* expansion. This approach cuts out a lot of noise from old/incompatible/abandoned/archived addons. However! the 'full' catalog has absolutely everything in it and is available from the `catalog` menu. Your addon may get a match there.

**Comment by torkus** [comment]
using the inverse colours from the current theme, I came up with this:

![Screenshot at 2019-12-28 18-15-04--inverted](https://user-images.githubusercontent.com/48790775/71540797-355c4600-299f-11ea-99bc-9711cb9d80a4.png)

I'll implement this for the 0.11.0 release with a menu option, but Java Swing has a very particular way of doing things using "Look and Feel" that I know almost nothing about so I'll investigate a more sophisticated approach to styling once 0.11.0 is out the door.

**Comment by torkus** [comment]
ok, this should make wowman usable for those with dark themes. Let me know if it's no good:

---

[wowman-0.11.0-unreleased.jar.zip](https://github.com/ogri-la/wowman/files/4007991/wowman-0.11.0-unreleased.jar.zip)
sha256: 72cbd9c47db3af68f427497f7bcd78fbae4457b2309da5240a4fbc52a800c432

---

work is happening here: https://github.com/ogri-la/wowman/pull/106

**Comment by layday** [comment]
The zip is broken but I built the branch from source and the theme switch has no effect on macOS, in case you were wondering.

**Comment by torkus** [comment]
The 'uberjar' process generates two files, one that is just the app and the other that bundles all of the dependencies together. Looks like I uploaded the wrong `.jar` file. 

---

[wowman-0.11.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/4011371/wowman-0.11.0-unreleased-standalone.jar.zip)
sha256: 391fca476518fbdc75a79f7cfe0576032157bee100f034537fa7322d4d6d4aa5

---

I'll test things on mac today before I release.

**Comment by torkus** [comment]
> the theme switch has no effect on macOS

the theme switch works as intended on Mojave, however the 'dark' mac theme doesn't appear to apply to Java Swing applications so switching colour sets isn't too useful

**Comment by torkus** [comment]
released, with 'dark' screenshots

I'll ping this issue again when I figure out how Swing wants me to do things properly.
