### ISSUE TITLE
Add support for addons.wago.io as a source

### ISSUE THREAD

**Issue by deadmeu** [ogri-la/wowman#439]
There are some add-ons, such as [Details](https://addons.wago.io/addons/details-damage-meter-standalone) that are not available in the current list of sources, but is available on Wago. Any chance we could see support for addons.wago.io as a source?

**Comment by torkus** [comment]
hey @deadmeu , I don't intend to support Wago at this time.

It seems pretty clear that, like Curseforge, they're hostile to addons being downloaded and installed outside of their own ecosystem. I'm certain I could circumvent it but I discovered with Curseforge and Tukui that supporting these sites is more trouble than it's worth.

And just like binary blobs on linux, it feels kind of icky to be dealing with them.

@layday's Instawow _does_ support Wago iirc.

**Comment by layday** [comment]
instawow supports Wago as a source but it's untested and, quite frankly, I doubt anyone's ever used it, since instawow also supports CF (behind ~~smoke and~~ mirrors), if you cannot do without.

**Comment by deadmeu** [comment]
That's a real shame, but I appreciate that it was at least considered. I only use strongbox for addon management because it's available as a Flatpak, so I guess I'll just have to manually manage those other addons myself.

@torkus have you considered enhancing the Github integration to support pulling the latest tag, or even a specific commit, to at least simplify the manual management process? [Details](https://github.com/Tercioo/Details-Damage-Meter) specifically doesn't seem to use Releases, but does seem to use tags quite frequently.

**Comment by torkus** [comment]
That feature is asked for often, either to clone a repository and manage it like one (switching branches, checking out tags, commits, etc) or to add support for downloading Github's automatic asset files.

Because Curseforge and Tukui have been pruned away then greater support for Github and Wowinterface seems reasonable. Unfortunately they are not on the roadmap for this year.

> have to manually manage those other addons myself

Strongbox supports installing addons from zip files: `File -> Install addon from file`

![Screenshot at 2024-11-26 18-15-22](https://github.com/user-attachments/assets/ac02a027-3077-4778-9a25-157cab621659)

I was going to say that the created and updated dates seem a bit off but it looks like it has been matched against an older version in the Wowinterface catalogue. The next step is right clicking on the addon and selecting `Ignore`. 

It's still quite manual but slightly better than unzipping using a filemanager.
