### ISSUE TITLE
F/OSS in comrades.csv

### ISSUE THREAD

**Issue by ilu33** [ogri-la/wowman#73]
https://github.com/ephraim/lcurse is free software.

These github repos are at least OSS (obviously, since on github):
https://github.com/cowdude/wowaddonmanager
https://github.com/Gonzih/wow-addon-manager
https://github.com/Mangmasta/MangManager
License is missing so we don't know whether they are free.

**Comment by torkus** [comment]
"free" is distinct from "Free/libre" in the Free/Open Source Software "F/OSS" abbreviation.

"Open Source" is not the same as "Source Available". 

The licence the authors of the software choose to use determines whether the software is classified as "F/OSS" or simply "Source Available". Software is not "Open Source" simply by existing on Github. Software with no licence is simply marked as "source available" and you use it at your own risk.

lcurse uses the "Unlicense", which is not on the list of OSI approved licences nor is it "Free/libre" software, although it is compatible for use with Free/libre software. This means it is *not* F/OSS software. Due to the weirdness of that licence it may not even be in the public domain properly.

Some further reading:

* https://en.wikipedia.org/wiki/Free_software
* https://en.wikipedia.org/wiki/Open-source_software
* https://opensource.org/licenses
* https://en.wikipedia.org/wiki/Unlicense and [problems with the Unlicence](https://web.archive.org/web/20170301020915/https://lists.opensource.org/pipermail/license-review/2012-January/001386.html)

**Comment by ilu33** [comment]
Yes, an organization has - rather successfully - tried to hijack the words "open" and "source". Which doesn't change their meaning. But if you follow OSI's definitions, keep things as they are.
