### ISSUE TITLE
Export directory

### ISSUE THREAD

**Issue by eVen-gits** [ogri-la/wowman#81]
Hello,

I've tried exporting the installed addons list, but it doesn't seem to actually respect the output directory.

**Error:** Output directory of addon export functionality is wrong.
**Steps to reproduce:** Try to export addon list into another directory.
**Expected result:** The file will have correct name, but will be saved to the same directory as .jar file

Similarly, it should suggest .json file extension (or automatically append it if none is specified).
Initially, I wanted to do the fix, but unfortunately, the language of the software is too foreign to me.

Best regards,
-E

**Comment by torkus** [comment]
thanks for reporting the bug, @eVen-gits 

I have another outstanding bug related to the export functionality so I'll take a look at them at the same time.

I added the export functionality on a bit of a whim, thinking it would be useful to get data *out* of the system. I didn't know who would actually use it or what they would use it for ... may I ask what you are using the export functionality for? 

> Initially, I wanted to do the fix, but unfortunately, the language of the software is too foreign to me.

ah well, thanks for making the effort regardless.

**Comment by eVen-gits** [comment]
Well, I figured it would be useful to store some of my own addon configs. Now, the WTF directory is easy enough to add to a repo as it's not too large, but the addons folder is rather large due to the assets that come with addons often.

So instead of backing up the whole addons folder (+they are usually updated regularly), it's better to backup a list - this is where your functionality came in handy.

Thanks for your good work, the piece of software has been very useful for me as a linux player.

**Comment by torkus** [comment]
Thanks for your feedback, @eVen-gits , it really is very useful. 

The bug has been found and fixed but the next release isn't due until December because November will be busy for me. Below is a pre-release with the path issue fixed if you'd like to try it out:

---
[wowman-0.11.0-unreleased-standalone.jar.zip](https://github.com/ogri-la/wowman/files/3793807/wowman-0.11.0-unreleased-standalone.jar.zip)
sha256: b35cccc1458bf12d9fc5a6aaa8ed60ced5965e36a000d12d9f7ee556c7dbc150

---

The export file will always get a `.json` extension no matter what other extension you may use. I may revisit the behaviour to make it friendlier or more obvious what it is doing.

The import/export feature is still quite undeveloped and may change in the future (suggest improvements!) but I'll try and keep it backwards compatible with the simple set of fields it's exporting now.

**Comment by torkus** [comment]
>  the next release isn't due until December

he said, releasing `0.10.1` :unamused: 

Unfortunately I didn't keep the fix to the bare minimum and it became too complicated to merge and release at this late hour (sorry).

**Comment by torkus** [comment]
Feel free to re-open the ticket if you consider the issue still isn't properly fixed.
