### ISSUE TITLE
Missing WowInterface addons from search tab

### ISSUE THREAD

**Issue by johlcar** [ogri-la/wowman#87]
Hello, thank you for building this application. As a Linux user, wowman is an awesome alternative to the Twitch app (that can retrieve from other remote hosts as well!).

I have been able to install all of my addons except for two, which are both from the WoWInterface site and do not show up under the search tab. These addons are:

TrinketMenuClassic (https://www.wowinterface.com/downloads/info24977-TrinketMenuClassic.html)
BetterAlign (https://www.wowinterface.com/downloads/info25040-BetterAlign.html)

Wowman thinks my TrinketMenu addon folder is the version discontinued from retail on the CurseForge site.

These addons haven't been updated in a while (and may not be), but they have both working without issue for me since release. Also, I have not been able to find alternatives to them.

**Comment by torkus** [comment]
hi @johlcar , thank you for the kind words.

I'm taking a look at these missing addons for you now. I've confirmed I can't see them in any of the catalogues available (from the 'Catalog' menu) which means both of these are in a very rare category of addons that wowinterface.com exclude from their API but are present on their website (affects about a dozen addons iirc) or, more likely, wowman isn't scraping the the 'classic' addon category properly. 

> Wowman thinks my TrinketMenu addon folder is the version discontinued from retail on the CurseForge site.

When wowman encounters an addon it tries to match it to an item in the catalogue. The standard catalogue is a mix of wowinterface and curseforge items and will attempt to match on the addon's name first followed by other less likely fields. It's likely it can't find a match in the wowinterface entries but that it does find an entry in the curseforge ones. It gets a little tricky but one problem at a time - I'll hunt down these missing addons and get back to you, then we can tackle re-installing the correct addons.

**Comment by torkus** [comment]
Alright, found the bug and re-generated the catalogues. At some point a fix I did previously to include the classic addons from wowinterface stopped working, thank you for catching it for me.

1. start wowman
2. from the top menu `Cache` -> `Clear catalogs`
3. restart wowman

search and your two addons should be present in the search results:

![Screenshot at 2019-11-06 01-11-30](https://user-images.githubusercontent.com/48790775/68217375-6a4cbc00-0032-11ea-9583-016651ccd43a.png)

You just need to re-install them now.

Because these are both classic addons with no 'retail' compatibility, your addons directory needs to have the 'classic' mode selected otherwise you'll get a warning like

> no 'retail' release available for 'trinket-menu-classic' on wowinterface

Let me know how you go

**Comment by johlcar** [comment]
It worked perfect! Thanks for your quick help with this issue.

**Comment by torkus** [comment]
my pleasure

**Comment by edricgarran** [comment]
This bug seems to still be happening.
Just had it happen with https://www.curseforge.com/wow/addons/vui/, it doesn't show up on search, but when I installed it manually, it appeared correctly in the installed addons and offered to update (which reinstalled the same version and probably saved it to the list).

**Comment by torkus** [comment]
taking a look

**Comment by torkus** [comment]
I think this might be a different issue. Trying typing 'visual' into the search box. Does it appear?

What I think is happening is that because the number of search results displayed is only 80 and the ElvUI results are dominating (and because I have no pagination), the 'vui' result isn't being displayed.

I'll open a separate issue to add pagination, thanks for raising the issue @edricgarran
